#!/usr/bin/env python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os
import sys

import chrome_proxy_config

sys.path.insert(1, chrome_proxy_config.TELEMETRY_DIR)

from telemetry import benchmark_runner


if __name__ == '__main__':
  sys.exit(benchmark_runner.main(chrome_proxy_config.Config(
      ['live_tests'])))
