#!/usr/bin/env python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""This script runs unit tests of the code in the perf directory.

This script DOES NOT run benchmarks. run_benchmark does that.
"""

import os
import sys

import chrome_proxy_config

sys.path.insert(1, chrome_proxy_config.TELEMETRY_DIR)

from telemetry.testing import unittest_runner


if __name__ == '__main__':
  sys.exit(unittest_runner.Run(chrome_proxy_config.Config(['integration_tests',
                                                           'live_tests'])))
