// Do not change directly - autogenerated by
// ./pnacl/unsupported/ppapi_pnacl_calling_conv_tool.py emit-testing-code

#include "everything.h"

// avoid c++ name mangling for better readability
extern "C" {

// cluster of identical function signatures
// PPB_AudioInput_Dev:0.2:EnumerateDevices
// PPB_VideoCapture_Dev:0.2:EnumerateDevices

extern int32_t PREFIX_INVOCATION(PPB_AudioInput_Dev_0_2_EnumerateDevices)(PP_Resource p0, PP_Resource* p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_AudioInput_Dev_0_2_EnumerateDevices)(PP_Resource p0, PP_Resource* p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_AudioInput_Dev_0_2_EnumerateDevices)(PP_Resource p0, PP_Resource* p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Resource_ptr(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_AudioInput_Dev:0.2:Open

extern int32_t PREFIX_INVOCATION(PPB_AudioInput_Dev_0_2_Open)(PP_Resource p0, PP_Resource p1, PP_Resource p2, PPB_AudioInput_Callback p3, void* p4, struct PP_CompletionCallback p5);
extern int32_t PREFIX_FUNCTION(PPB_AudioInput_Dev_0_2_Open)(PP_Resource p0, PP_Resource p1, PP_Resource p2, PPB_AudioInput_Callback p3, void* p4, struct PP_CompletionCallback p5) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_AudioInput_Dev_0_2_Open)(PP_Resource p0, PP_Resource p1, PP_Resource p2, PPB_AudioInput_Callback p3, void* p4, struct PP_CompletionCallback p5) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Resource(p1);
  emit_value_PP_Resource(p2);
  emit_value_PPB_AudioInput_Callback(p3);
  emit_value_void_ptr(p4);
  emit_value_struct_PP_CompletionCallback(p5);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_Console_Dev:0.1:Log

extern void PREFIX_INVOCATION(PPB_Console_Dev_0_1_Log)(PP_Instance p0, PP_LogLevel_Dev p1, struct PP_Var p2);
extern void PREFIX_FUNCTION(PPB_Console_Dev_0_1_Log)(PP_Instance p0, PP_LogLevel_Dev p1, struct PP_Var p2) __attribute__((noinline));

void PREFIX_FUNCTION(PPB_Console_Dev_0_1_Log)(PP_Instance p0, PP_LogLevel_Dev p1, struct PP_Var p2) {
  emit_value_PP_Instance(p0);
  emit_value_PP_LogLevel_Dev(p1);
  emit_value_struct_PP_Var(p2);
}

// cluster of identical function signatures
// PPB_Console_Dev:0.1:LogWithSource

extern void PREFIX_INVOCATION(PPB_Console_Dev_0_1_LogWithSource)(PP_Instance p0, PP_LogLevel_Dev p1, struct PP_Var p2, struct PP_Var p3);
extern void PREFIX_FUNCTION(PPB_Console_Dev_0_1_LogWithSource)(PP_Instance p0, PP_LogLevel_Dev p1, struct PP_Var p2, struct PP_Var p3) __attribute__((noinline));

void PREFIX_FUNCTION(PPB_Console_Dev_0_1_LogWithSource)(PP_Instance p0, PP_LogLevel_Dev p1, struct PP_Var p2, struct PP_Var p3) {
  emit_value_PP_Instance(p0);
  emit_value_PP_LogLevel_Dev(p1);
  emit_value_struct_PP_Var(p2);
  emit_value_struct_PP_Var(p3);
}

// cluster of identical function signatures
// PPB_Core:1.0:CallOnMainThread

extern void PREFIX_INVOCATION(PPB_Core_1_0_CallOnMainThread)(int32_t p0, struct PP_CompletionCallback p1, int32_t p2);
extern void PREFIX_FUNCTION(PPB_Core_1_0_CallOnMainThread)(int32_t p0, struct PP_CompletionCallback p1, int32_t p2) __attribute__((noinline));

void PREFIX_FUNCTION(PPB_Core_1_0_CallOnMainThread)(int32_t p0, struct PP_CompletionCallback p1, int32_t p2) {
  emit_value_int32_t(p0);
  emit_value_struct_PP_CompletionCallback(p1);
  emit_value_int32_t(p2);
}

// cluster of identical function signatures
// PPB_DeviceRef_Dev:0.1:GetName
// PPB_FileRef:1.0:GetName
// PPB_FileRef:1.0:GetPath
// PPB_IMEInputEvent_Dev:0.1:GetText
// PPB_KeyboardInputEvent:1.0:GetCharacterText
// PPB_WebSocket:1.0:GetCloseReason
// PPB_WebSocket:1.0:GetExtensions
// PPB_WebSocket:1.0:GetProtocol
// PPB_WebSocket:1.0:GetURL

extern struct PP_Var PREFIX_INVOCATION(PPB_DeviceRef_Dev_0_1_GetName)(PP_Resource p0);
extern struct PP_Var PREFIX_FUNCTION(PPB_DeviceRef_Dev_0_1_GetName)(PP_Resource p0) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_DeviceRef_Dev_0_1_GetName)(PP_Resource p0) {
  emit_value_PP_Resource(p0);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_FileChooser_Dev:0.5:Create

extern PP_Resource PREFIX_INVOCATION(PPB_FileChooser_Dev_0_5_Create)(PP_Instance p0, PP_FileChooserMode_Dev p1, struct PP_Var p2);
extern PP_Resource PREFIX_FUNCTION(PPB_FileChooser_Dev_0_5_Create)(PP_Instance p0, PP_FileChooserMode_Dev p1, struct PP_Var p2) __attribute__((noinline));

PP_Resource PREFIX_FUNCTION(PPB_FileChooser_Dev_0_5_Create)(PP_Instance p0, PP_FileChooserMode_Dev p1, struct PP_Var p2) {
  emit_value_PP_Instance(p0);
  emit_value_PP_FileChooserMode_Dev(p1);
  emit_value_struct_PP_Var(p2);
  return get_value_PP_Resource();
}

// cluster of identical function signatures
// PPB_FileChooser_Dev:0.5:Show
// PPB_FileIO:1.0:Flush
// PPB_FileRef:1.0:Delete
// PPB_Graphics2D:1.0:Flush
// PPB_Graphics3D:1.0:SwapBuffers
// PPB_URLLoader:1.0:FinishStreamingToFile
// PPB_URLLoader:1.0:FollowRedirect
// PPB_VideoDecoder_Dev:0.16:Flush
// PPB_VideoDecoder_Dev:0.16:Reset

extern int32_t PREFIX_INVOCATION(PPB_FileChooser_Dev_0_5_Show)(PP_Resource p0, struct PP_CompletionCallback p1);
extern int32_t PREFIX_FUNCTION(PPB_FileChooser_Dev_0_5_Show)(PP_Resource p0, struct PP_CompletionCallback p1) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileChooser_Dev_0_5_Show)(PP_Resource p0, struct PP_CompletionCallback p1) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_CompletionCallback(p1);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileChooser_Dev:0.6:Show

extern int32_t PREFIX_INVOCATION(PPB_FileChooser_Dev_0_6_Show)(PP_Resource p0, struct PP_ArrayOutput p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_FileChooser_Dev_0_6_Show)(PP_Resource p0, struct PP_ArrayOutput p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileChooser_Dev_0_6_Show)(PP_Resource p0, struct PP_ArrayOutput p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_ArrayOutput(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileIO:1.0:Open

extern int32_t PREFIX_INVOCATION(PPB_FileIO_1_0_Open)(PP_Resource p0, PP_Resource p1, int32_t p2, struct PP_CompletionCallback p3);
extern int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Open)(PP_Resource p0, PP_Resource p1, int32_t p2, struct PP_CompletionCallback p3) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Open)(PP_Resource p0, PP_Resource p1, int32_t p2, struct PP_CompletionCallback p3) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Resource(p1);
  emit_value_int32_t(p2);
  emit_value_struct_PP_CompletionCallback(p3);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileIO:1.0:Query

extern int32_t PREFIX_INVOCATION(PPB_FileIO_1_0_Query)(PP_Resource p0, struct PP_FileInfo* p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Query)(PP_Resource p0, struct PP_FileInfo* p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Query)(PP_Resource p0, struct PP_FileInfo* p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_FileInfo_ptr(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileIO:1.0:Read

extern int32_t PREFIX_INVOCATION(PPB_FileIO_1_0_Read)(PP_Resource p0, int64_t p1, char* p2, int32_t p3, struct PP_CompletionCallback p4);
extern int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Read)(PP_Resource p0, int64_t p1, char* p2, int32_t p3, struct PP_CompletionCallback p4) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Read)(PP_Resource p0, int64_t p1, char* p2, int32_t p3, struct PP_CompletionCallback p4) {
  emit_value_PP_Resource(p0);
  emit_value_int64_t(p1);
  emit_value_char_ptr(p2);
  emit_value_int32_t(p3);
  emit_value_struct_PP_CompletionCallback(p4);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileIO:1.0:SetLength
// PPB_FileSystem:1.0:Open

extern int32_t PREFIX_INVOCATION(PPB_FileIO_1_0_SetLength)(PP_Resource p0, int64_t p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_SetLength)(PP_Resource p0, int64_t p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_SetLength)(PP_Resource p0, int64_t p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_int64_t(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileIO:1.0:Touch
// PPB_FileRef:1.0:Touch

extern int32_t PREFIX_INVOCATION(PPB_FileIO_1_0_Touch)(PP_Resource p0, PP_Time p1, PP_Time p2, struct PP_CompletionCallback p3);
extern int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Touch)(PP_Resource p0, PP_Time p1, PP_Time p2, struct PP_CompletionCallback p3) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Touch)(PP_Resource p0, PP_Time p1, PP_Time p2, struct PP_CompletionCallback p3) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Time(p1);
  emit_value_PP_Time(p2);
  emit_value_struct_PP_CompletionCallback(p3);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileIO:1.0:Write

extern int32_t PREFIX_INVOCATION(PPB_FileIO_1_0_Write)(PP_Resource p0, int64_t p1, const char* p2, int32_t p3, struct PP_CompletionCallback p4);
extern int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Write)(PP_Resource p0, int64_t p1, const char* p2, int32_t p3, struct PP_CompletionCallback p4) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileIO_1_0_Write)(PP_Resource p0, int64_t p1, const char* p2, int32_t p3, struct PP_CompletionCallback p4) {
  emit_value_PP_Resource(p0);
  emit_value_int64_t(p1);
  emit_value_char_ptr(p2);
  emit_value_int32_t(p3);
  emit_value_struct_PP_CompletionCallback(p4);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileRef:1.0:MakeDirectory

extern int32_t PREFIX_INVOCATION(PPB_FileRef_1_0_MakeDirectory)(PP_Resource p0, PP_Bool p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_FileRef_1_0_MakeDirectory)(PP_Resource p0, PP_Bool p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileRef_1_0_MakeDirectory)(PP_Resource p0, PP_Bool p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Bool(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_FileRef:1.0:Rename
// PPB_URLLoader:1.0:Open

extern int32_t PREFIX_INVOCATION(PPB_FileRef_1_0_Rename)(PP_Resource p0, PP_Resource p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_FileRef_1_0_Rename)(PP_Resource p0, PP_Resource p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_FileRef_1_0_Rename)(PP_Resource p0, PP_Resource p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Resource(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_Font_Dev:0.6:GetFontFamilies

extern struct PP_Var PREFIX_INVOCATION(PPB_Font_Dev_0_6_GetFontFamilies)(PP_Instance p0);
extern struct PP_Var PREFIX_FUNCTION(PPB_Font_Dev_0_6_GetFontFamilies)(PP_Instance p0) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_Font_Dev_0_6_GetFontFamilies)(PP_Instance p0) {
  emit_value_PP_Instance(p0);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_IMEInputEvent_Dev:0.2:Create

extern PP_Resource PREFIX_INVOCATION(PPB_IMEInputEvent_Dev_0_2_Create)(PP_Instance p0, PP_InputEvent_Type p1, PP_TimeTicks p2, struct PP_Var p3, uint32_t p4, const uint32_t* p5, int32_t p6, uint32_t p7, uint32_t p8);
extern PP_Resource PREFIX_FUNCTION(PPB_IMEInputEvent_Dev_0_2_Create)(PP_Instance p0, PP_InputEvent_Type p1, PP_TimeTicks p2, struct PP_Var p3, uint32_t p4, const uint32_t* p5, int32_t p6, uint32_t p7, uint32_t p8) __attribute__((noinline));

PP_Resource PREFIX_FUNCTION(PPB_IMEInputEvent_Dev_0_2_Create)(PP_Instance p0, PP_InputEvent_Type p1, PP_TimeTicks p2, struct PP_Var p3, uint32_t p4, const uint32_t* p5, int32_t p6, uint32_t p7, uint32_t p8) {
  emit_value_PP_Instance(p0);
  emit_value_PP_InputEvent_Type(p1);
  emit_value_PP_TimeTicks(p2);
  emit_value_struct_PP_Var(p3);
  emit_value_uint32_t(p4);
  emit_value_uint32_t_ptr(p5);
  emit_value_int32_t(p6);
  emit_value_uint32_t(p7);
  emit_value_uint32_t(p8);
  return get_value_PP_Resource();
}

// cluster of identical function signatures
// PPB_KeyboardInputEvent:1.0:Create

extern PP_Resource PREFIX_INVOCATION(PPB_KeyboardInputEvent_1_0_Create)(PP_Instance p0, PP_InputEvent_Type p1, PP_TimeTicks p2, uint32_t p3, uint32_t p4, struct PP_Var p5);
extern PP_Resource PREFIX_FUNCTION(PPB_KeyboardInputEvent_1_0_Create)(PP_Instance p0, PP_InputEvent_Type p1, PP_TimeTicks p2, uint32_t p3, uint32_t p4, struct PP_Var p5) __attribute__((noinline));

PP_Resource PREFIX_FUNCTION(PPB_KeyboardInputEvent_1_0_Create)(PP_Instance p0, PP_InputEvent_Type p1, PP_TimeTicks p2, uint32_t p3, uint32_t p4, struct PP_Var p5) {
  emit_value_PP_Instance(p0);
  emit_value_PP_InputEvent_Type(p1);
  emit_value_PP_TimeTicks(p2);
  emit_value_uint32_t(p3);
  emit_value_uint32_t(p4);
  emit_value_struct_PP_Var(p5);
  return get_value_PP_Resource();
}

// cluster of identical function signatures
// PPB_MessageLoop_Dev:0.1:PostWork

extern int32_t PREFIX_INVOCATION(PPB_MessageLoop_Dev_0_1_PostWork)(PP_Resource p0, struct PP_CompletionCallback p1, int64_t p2);
extern int32_t PREFIX_FUNCTION(PPB_MessageLoop_Dev_0_1_PostWork)(PP_Resource p0, struct PP_CompletionCallback p1, int64_t p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_MessageLoop_Dev_0_1_PostWork)(PP_Resource p0, struct PP_CompletionCallback p1, int64_t p2) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_CompletionCallback(p1);
  emit_value_int64_t(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_Messaging:1.0:PostMessage
// PPP_Messaging:1.0:HandleMessage

extern void PREFIX_INVOCATION(PPB_Messaging_1_0_PostMessage)(PP_Instance p0, struct PP_Var p1);
extern void PREFIX_FUNCTION(PPB_Messaging_1_0_PostMessage)(PP_Instance p0, struct PP_Var p1) __attribute__((noinline));

void PREFIX_FUNCTION(PPB_Messaging_1_0_PostMessage)(PP_Instance p0, struct PP_Var p1) {
  emit_value_PP_Instance(p0);
  emit_value_struct_PP_Var(p1);
}

// cluster of identical function signatures
// PPB_MouseInputEvent:1.1:GetMovement

extern struct PP_Point PREFIX_INVOCATION(PPB_MouseInputEvent_1_1_GetMovement)(PP_Resource p0);
extern struct PP_Point PREFIX_FUNCTION(PPB_MouseInputEvent_1_1_GetMovement)(PP_Resource p0) __attribute__((noinline));

struct PP_Point PREFIX_FUNCTION(PPB_MouseInputEvent_1_1_GetMovement)(PP_Resource p0) {
  emit_value_PP_Resource(p0);
  return get_value_struct_PP_Point();
}

// cluster of identical function signatures
// PPB_MouseLock:1.0:LockMouse

extern int32_t PREFIX_INVOCATION(PPB_MouseLock_1_0_LockMouse)(PP_Instance p0, struct PP_CompletionCallback p1);
extern int32_t PREFIX_FUNCTION(PPB_MouseLock_1_0_LockMouse)(PP_Instance p0, struct PP_CompletionCallback p1) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_MouseLock_1_0_LockMouse)(PP_Instance p0, struct PP_CompletionCallback p1) {
  emit_value_PP_Instance(p0);
  emit_value_struct_PP_CompletionCallback(p1);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_Printing_Dev:0.7:GetDefaultPrintSettings

extern int32_t PREFIX_INVOCATION(PPB_Printing_Dev_0_7_GetDefaultPrintSettings)(PP_Resource p0, struct PP_PrintSettings_Dev* p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_Printing_Dev_0_7_GetDefaultPrintSettings)(PP_Resource p0, struct PP_PrintSettings_Dev* p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_Printing_Dev_0_7_GetDefaultPrintSettings)(PP_Resource p0, struct PP_PrintSettings_Dev* p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_PrintSettings_Dev_ptr(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_Testing_Dev:0.9:GetDocumentURL
// PPB_URLUtil_Dev:0.6:GetDocumentURL
// PPB_URLUtil_Dev:0.6:GetPluginInstanceURL

extern struct PP_Var PREFIX_INVOCATION(PPB_Testing_Dev_0_9_GetDocumentURL)(PP_Instance p0, struct PP_URLComponents_Dev* p1);
extern struct PP_Var PREFIX_FUNCTION(PPB_Testing_Dev_0_9_GetDocumentURL)(PP_Instance p0, struct PP_URLComponents_Dev* p1) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_Testing_Dev_0_9_GetDocumentURL)(PP_Instance p0, struct PP_URLComponents_Dev* p1) {
  emit_value_PP_Instance(p0);
  emit_value_struct_PP_URLComponents_Dev_ptr(p1);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_TouchInputEvent:1.0:GetTouchById
// PPB_TouchInputEvent:1.0:GetTouchByIndex

extern struct PP_TouchPoint PREFIX_INVOCATION(PPB_TouchInputEvent_1_0_GetTouchById)(PP_Resource p0, PP_TouchListType p1, uint32_t p2);
extern struct PP_TouchPoint PREFIX_FUNCTION(PPB_TouchInputEvent_1_0_GetTouchById)(PP_Resource p0, PP_TouchListType p1, uint32_t p2) __attribute__((noinline));

struct PP_TouchPoint PREFIX_FUNCTION(PPB_TouchInputEvent_1_0_GetTouchById)(PP_Resource p0, PP_TouchListType p1, uint32_t p2) {
  emit_value_PP_Resource(p0);
  emit_value_PP_TouchListType(p1);
  emit_value_uint32_t(p2);
  return get_value_struct_PP_TouchPoint();
}

// cluster of identical function signatures
// PPB_URLLoader:1.0:ReadResponseBody

extern int32_t PREFIX_INVOCATION(PPB_URLLoader_1_0_ReadResponseBody)(PP_Resource p0, void* p1, int32_t p2, struct PP_CompletionCallback p3);
extern int32_t PREFIX_FUNCTION(PPB_URLLoader_1_0_ReadResponseBody)(PP_Resource p0, void* p1, int32_t p2, struct PP_CompletionCallback p3) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_URLLoader_1_0_ReadResponseBody)(PP_Resource p0, void* p1, int32_t p2, struct PP_CompletionCallback p3) {
  emit_value_PP_Resource(p0);
  emit_value_void_ptr(p1);
  emit_value_int32_t(p2);
  emit_value_struct_PP_CompletionCallback(p3);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_URLRequestInfo:1.0:SetProperty

extern PP_Bool PREFIX_INVOCATION(PPB_URLRequestInfo_1_0_SetProperty)(PP_Resource p0, PP_URLRequestProperty p1, struct PP_Var p2);
extern PP_Bool PREFIX_FUNCTION(PPB_URLRequestInfo_1_0_SetProperty)(PP_Resource p0, PP_URLRequestProperty p1, struct PP_Var p2) __attribute__((noinline));

PP_Bool PREFIX_FUNCTION(PPB_URLRequestInfo_1_0_SetProperty)(PP_Resource p0, PP_URLRequestProperty p1, struct PP_Var p2) {
  emit_value_PP_Resource(p0);
  emit_value_PP_URLRequestProperty(p1);
  emit_value_struct_PP_Var(p2);
  return get_value_PP_Bool();
}

// cluster of identical function signatures
// PPB_URLResponseInfo:1.0:GetProperty

extern struct PP_Var PREFIX_INVOCATION(PPB_URLResponseInfo_1_0_GetProperty)(PP_Resource p0, PP_URLResponseProperty p1);
extern struct PP_Var PREFIX_FUNCTION(PPB_URLResponseInfo_1_0_GetProperty)(PP_Resource p0, PP_URLResponseProperty p1) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_URLResponseInfo_1_0_GetProperty)(PP_Resource p0, PP_URLResponseProperty p1) {
  emit_value_PP_Resource(p0);
  emit_value_PP_URLResponseProperty(p1);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_URLUtil_Dev:0.6:Canonicalize

extern struct PP_Var PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_Canonicalize)(struct PP_Var p0, struct PP_URLComponents_Dev* p1);
extern struct PP_Var PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_Canonicalize)(struct PP_Var p0, struct PP_URLComponents_Dev* p1) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_Canonicalize)(struct PP_Var p0, struct PP_URLComponents_Dev* p1) {
  emit_value_struct_PP_Var(p0);
  emit_value_struct_PP_URLComponents_Dev_ptr(p1);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_URLUtil_Dev:0.6:DocumentCanRequest

extern PP_Bool PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_DocumentCanRequest)(PP_Instance p0, struct PP_Var p1);
extern PP_Bool PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_DocumentCanRequest)(PP_Instance p0, struct PP_Var p1) __attribute__((noinline));

PP_Bool PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_DocumentCanRequest)(PP_Instance p0, struct PP_Var p1) {
  emit_value_PP_Instance(p0);
  emit_value_struct_PP_Var(p1);
  return get_value_PP_Bool();
}

// cluster of identical function signatures
// PPB_URLUtil_Dev:0.6:IsSameSecurityOrigin

extern PP_Bool PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_IsSameSecurityOrigin)(struct PP_Var p0, struct PP_Var p1);
extern PP_Bool PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_IsSameSecurityOrigin)(struct PP_Var p0, struct PP_Var p1) __attribute__((noinline));

PP_Bool PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_IsSameSecurityOrigin)(struct PP_Var p0, struct PP_Var p1) {
  emit_value_struct_PP_Var(p0);
  emit_value_struct_PP_Var(p1);
  return get_value_PP_Bool();
}

// cluster of identical function signatures
// PPB_URLUtil_Dev:0.6:ResolveRelativeToDocument

extern struct PP_Var PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_ResolveRelativeToDocument)(PP_Instance p0, struct PP_Var p1, struct PP_URLComponents_Dev* p2);
extern struct PP_Var PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_ResolveRelativeToDocument)(PP_Instance p0, struct PP_Var p1, struct PP_URLComponents_Dev* p2) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_ResolveRelativeToDocument)(PP_Instance p0, struct PP_Var p1, struct PP_URLComponents_Dev* p2) {
  emit_value_PP_Instance(p0);
  emit_value_struct_PP_Var(p1);
  emit_value_struct_PP_URLComponents_Dev_ptr(p2);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_URLUtil_Dev:0.6:ResolveRelativeToURL

extern struct PP_Var PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_ResolveRelativeToURL)(struct PP_Var p0, struct PP_Var p1, struct PP_URLComponents_Dev* p2);
extern struct PP_Var PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_ResolveRelativeToURL)(struct PP_Var p0, struct PP_Var p1, struct PP_URLComponents_Dev* p2) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_URLUtil_Dev_0_6_ResolveRelativeToURL)(struct PP_Var p0, struct PP_Var p1, struct PP_URLComponents_Dev* p2) {
  emit_value_struct_PP_Var(p0);
  emit_value_struct_PP_Var(p1);
  emit_value_struct_PP_URLComponents_Dev_ptr(p2);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_Var:1.0:AddRef
// PPB_Var:1.0:Release
// PPB_VarArrayBuffer:1.0:Unmap

extern void PREFIX_INVOCATION(PPB_Var_1_0_AddRef)(struct PP_Var p0);
extern void PREFIX_FUNCTION(PPB_Var_1_0_AddRef)(struct PP_Var p0) __attribute__((noinline));

void PREFIX_FUNCTION(PPB_Var_1_0_AddRef)(struct PP_Var p0) {
  emit_value_struct_PP_Var(p0);
}

// cluster of identical function signatures
// PPB_Var:1.0:VarFromUtf8

extern struct PP_Var PREFIX_INVOCATION(PPB_Var_1_0_VarFromUtf8)(PP_Module p0, const char* p1, uint32_t p2);
extern struct PP_Var PREFIX_FUNCTION(PPB_Var_1_0_VarFromUtf8)(PP_Module p0, const char* p1, uint32_t p2) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_Var_1_0_VarFromUtf8)(PP_Module p0, const char* p1, uint32_t p2) {
  emit_value_PP_Module(p0);
  emit_value_char_ptr(p1);
  emit_value_uint32_t(p2);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_Var:1.0:VarToUtf8

extern const char* PREFIX_INVOCATION(PPB_Var_1_0_VarToUtf8)(struct PP_Var p0, uint32_t* p1);
extern const char* PREFIX_FUNCTION(PPB_Var_1_0_VarToUtf8)(struct PP_Var p0, uint32_t* p1) __attribute__((noinline));

const char* PREFIX_FUNCTION(PPB_Var_1_0_VarToUtf8)(struct PP_Var p0, uint32_t* p1) {
  emit_value_struct_PP_Var(p0);
  emit_value_uint32_t_ptr(p1);
  return get_value_char_ptr();
}

// cluster of identical function signatures
// PPB_Var:1.1:VarFromUtf8

extern struct PP_Var PREFIX_INVOCATION(PPB_Var_1_1_VarFromUtf8)(const char* p0, uint32_t p1);
extern struct PP_Var PREFIX_FUNCTION(PPB_Var_1_1_VarFromUtf8)(const char* p0, uint32_t p1) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_Var_1_1_VarFromUtf8)(const char* p0, uint32_t p1) {
  emit_value_char_ptr(p0);
  emit_value_uint32_t(p1);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_VarArrayBuffer:1.0:ByteLength

extern PP_Bool PREFIX_INVOCATION(PPB_VarArrayBuffer_1_0_ByteLength)(struct PP_Var p0, uint32_t* p1);
extern PP_Bool PREFIX_FUNCTION(PPB_VarArrayBuffer_1_0_ByteLength)(struct PP_Var p0, uint32_t* p1) __attribute__((noinline));

PP_Bool PREFIX_FUNCTION(PPB_VarArrayBuffer_1_0_ByteLength)(struct PP_Var p0, uint32_t* p1) {
  emit_value_struct_PP_Var(p0);
  emit_value_uint32_t_ptr(p1);
  return get_value_PP_Bool();
}

// cluster of identical function signatures
// PPB_VarArrayBuffer:1.0:Create

extern struct PP_Var PREFIX_INVOCATION(PPB_VarArrayBuffer_1_0_Create)(uint32_t p0);
extern struct PP_Var PREFIX_FUNCTION(PPB_VarArrayBuffer_1_0_Create)(uint32_t p0) __attribute__((noinline));

struct PP_Var PREFIX_FUNCTION(PPB_VarArrayBuffer_1_0_Create)(uint32_t p0) {
  emit_value_uint32_t(p0);
  return get_value_struct_PP_Var();
}

// cluster of identical function signatures
// PPB_VarArrayBuffer:1.0:Map

extern void* PREFIX_INVOCATION(PPB_VarArrayBuffer_1_0_Map)(struct PP_Var p0);
extern void* PREFIX_FUNCTION(PPB_VarArrayBuffer_1_0_Map)(struct PP_Var p0) __attribute__((noinline));

void* PREFIX_FUNCTION(PPB_VarArrayBuffer_1_0_Map)(struct PP_Var p0) {
  emit_value_struct_PP_Var(p0);
  return get_value_void_ptr();
}

// cluster of identical function signatures
// PPB_VideoCapture_Dev:0.2:Open

extern int32_t PREFIX_INVOCATION(PPB_VideoCapture_Dev_0_2_Open)(PP_Resource p0, PP_Resource p1, const struct PP_VideoCaptureDeviceInfo_Dev* p2, uint32_t p3, struct PP_CompletionCallback p4);
extern int32_t PREFIX_FUNCTION(PPB_VideoCapture_Dev_0_2_Open)(PP_Resource p0, PP_Resource p1, const struct PP_VideoCaptureDeviceInfo_Dev* p2, uint32_t p3, struct PP_CompletionCallback p4) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_VideoCapture_Dev_0_2_Open)(PP_Resource p0, PP_Resource p1, const struct PP_VideoCaptureDeviceInfo_Dev* p2, uint32_t p3, struct PP_CompletionCallback p4) {
  emit_value_PP_Resource(p0);
  emit_value_PP_Resource(p1);
  emit_value_struct_PP_VideoCaptureDeviceInfo_Dev_ptr(p2);
  emit_value_uint32_t(p3);
  emit_value_struct_PP_CompletionCallback(p4);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_VideoDecoder_Dev:0.16:Decode

extern int32_t PREFIX_INVOCATION(PPB_VideoDecoder_Dev_0_16_Decode)(PP_Resource p0, const struct PP_VideoBitstreamBuffer_Dev* p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_VideoDecoder_Dev_0_16_Decode)(PP_Resource p0, const struct PP_VideoBitstreamBuffer_Dev* p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_VideoDecoder_Dev_0_16_Decode)(PP_Resource p0, const struct PP_VideoBitstreamBuffer_Dev* p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_VideoBitstreamBuffer_Dev_ptr(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_WebSocket:1.0:Close

extern int32_t PREFIX_INVOCATION(PPB_WebSocket_1_0_Close)(PP_Resource p0, uint16_t p1, struct PP_Var p2, struct PP_CompletionCallback p3);
extern int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_Close)(PP_Resource p0, uint16_t p1, struct PP_Var p2, struct PP_CompletionCallback p3) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_Close)(PP_Resource p0, uint16_t p1, struct PP_Var p2, struct PP_CompletionCallback p3) {
  emit_value_PP_Resource(p0);
  emit_value_uint16_t(p1);
  emit_value_struct_PP_Var(p2);
  emit_value_struct_PP_CompletionCallback(p3);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_WebSocket:1.0:Connect

extern int32_t PREFIX_INVOCATION(PPB_WebSocket_1_0_Connect)(PP_Resource p0, struct PP_Var p1, const struct PP_Var* p2, uint32_t p3, struct PP_CompletionCallback p4);
extern int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_Connect)(PP_Resource p0, struct PP_Var p1, const struct PP_Var* p2, uint32_t p3, struct PP_CompletionCallback p4) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_Connect)(PP_Resource p0, struct PP_Var p1, const struct PP_Var* p2, uint32_t p3, struct PP_CompletionCallback p4) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_Var(p1);
  emit_value_struct_PP_Var_ptr(p2);
  emit_value_uint32_t(p3);
  emit_value_struct_PP_CompletionCallback(p4);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_WebSocket:1.0:ReceiveMessage

extern int32_t PREFIX_INVOCATION(PPB_WebSocket_1_0_ReceiveMessage)(PP_Resource p0, struct PP_Var* p1, struct PP_CompletionCallback p2);
extern int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_ReceiveMessage)(PP_Resource p0, struct PP_Var* p1, struct PP_CompletionCallback p2) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_ReceiveMessage)(PP_Resource p0, struct PP_Var* p1, struct PP_CompletionCallback p2) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_Var_ptr(p1);
  emit_value_struct_PP_CompletionCallback(p2);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_WebSocket:1.0:SendMessage

extern int32_t PREFIX_INVOCATION(PPB_WebSocket_1_0_SendMessage)(PP_Resource p0, struct PP_Var p1);
extern int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_SendMessage)(PP_Resource p0, struct PP_Var p1) __attribute__((noinline));

int32_t PREFIX_FUNCTION(PPB_WebSocket_1_0_SendMessage)(PP_Resource p0, struct PP_Var p1) {
  emit_value_PP_Resource(p0);
  emit_value_struct_PP_Var(p1);
  return get_value_int32_t();
}

// cluster of identical function signatures
// PPB_WheelInputEvent:1.0:GetDelta
// PPB_WheelInputEvent:1.0:GetTicks

extern struct PP_FloatPoint PREFIX_INVOCATION(PPB_WheelInputEvent_1_0_GetDelta)(PP_Resource p0);
extern struct PP_FloatPoint PREFIX_FUNCTION(PPB_WheelInputEvent_1_0_GetDelta)(PP_Resource p0) __attribute__((noinline));

struct PP_FloatPoint PREFIX_FUNCTION(PPB_WheelInputEvent_1_0_GetDelta)(PP_Resource p0) {
  emit_value_PP_Resource(p0);
  return get_value_struct_PP_FloatPoint();
}
void PREFIX_FUNCTION(test_all)() {
  new_test("PPB_AudioInput_Dev_0_2_EnumerateDevices");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Resource* p1 = get_value_PP_Resource_ptr();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_AudioInput_Dev_0_2_EnumerateDevices)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_AudioInput_Dev_0_2_Open");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Resource p1 = get_value_PP_Resource();
    PP_Resource p2 = get_value_PP_Resource();
    PPB_AudioInput_Callback p3 = get_value_PPB_AudioInput_Callback();
    void* p4 = get_value_void_ptr();
    struct PP_CompletionCallback p5 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_AudioInput_Dev_0_2_Open)(p0, p1, p2, p3, p4, p5);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_Console_Dev_0_1_Log");
  {
    PP_Instance p0 = get_value_PP_Instance();
    PP_LogLevel_Dev p1 = get_value_PP_LogLevel_Dev();
    struct PP_Var p2 = get_value_struct_PP_Var();
    PREFIX_INVOCATION(PPB_Console_Dev_0_1_Log)(p0, p1, p2);
  }
  new_test("PPB_Console_Dev_0_1_LogWithSource");
  {
    PP_Instance p0 = get_value_PP_Instance();
    PP_LogLevel_Dev p1 = get_value_PP_LogLevel_Dev();
    struct PP_Var p2 = get_value_struct_PP_Var();
    struct PP_Var p3 = get_value_struct_PP_Var();
    PREFIX_INVOCATION(PPB_Console_Dev_0_1_LogWithSource)(p0, p1, p2, p3);
  }
  new_test("PPB_Core_1_0_CallOnMainThread");
  {
    int32_t p0 = get_value_int32_t();
    struct PP_CompletionCallback p1 = get_value_struct_PP_CompletionCallback();
    int32_t p2 = get_value_int32_t();
    PREFIX_INVOCATION(PPB_Core_1_0_CallOnMainThread)(p0, p1, p2);
  }
  new_test("PPB_DeviceRef_Dev_0_1_GetName");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_Var res = PREFIX_INVOCATION(PPB_DeviceRef_Dev_0_1_GetName)(p0);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_FileChooser_Dev_0_5_Create");
  {
    PP_Instance p0 = get_value_PP_Instance();
    PP_FileChooserMode_Dev p1 = get_value_PP_FileChooserMode_Dev();
    struct PP_Var p2 = get_value_struct_PP_Var();
    PP_Resource res = PREFIX_INVOCATION(PPB_FileChooser_Dev_0_5_Create)(p0, p1, p2);
    emit_string("result:");
    emit_value_PP_Resource(res);
  }
  new_test("PPB_FileChooser_Dev_0_5_Show");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_CompletionCallback p1 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileChooser_Dev_0_5_Show)(p0, p1);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileChooser_Dev_0_6_Show");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_ArrayOutput p1 = get_value_struct_PP_ArrayOutput();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileChooser_Dev_0_6_Show)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileIO_1_0_Open");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Resource p1 = get_value_PP_Resource();
    int32_t p2 = get_value_int32_t();
    struct PP_CompletionCallback p3 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileIO_1_0_Open)(p0, p1, p2, p3);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileIO_1_0_Query");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_FileInfo* p1 = get_value_struct_PP_FileInfo_ptr();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileIO_1_0_Query)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileIO_1_0_Read");
  {
    PP_Resource p0 = get_value_PP_Resource();
    int64_t p1 = get_value_int64_t();
    char* p2 = get_value_char_ptr();
    int32_t p3 = get_value_int32_t();
    struct PP_CompletionCallback p4 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileIO_1_0_Read)(p0, p1, p2, p3, p4);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileIO_1_0_SetLength");
  {
    PP_Resource p0 = get_value_PP_Resource();
    int64_t p1 = get_value_int64_t();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileIO_1_0_SetLength)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileIO_1_0_Touch");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Time p1 = get_value_PP_Time();
    PP_Time p2 = get_value_PP_Time();
    struct PP_CompletionCallback p3 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileIO_1_0_Touch)(p0, p1, p2, p3);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileIO_1_0_Write");
  {
    PP_Resource p0 = get_value_PP_Resource();
    int64_t p1 = get_value_int64_t();
    const char* p2 = get_value_char_ptr();
    int32_t p3 = get_value_int32_t();
    struct PP_CompletionCallback p4 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileIO_1_0_Write)(p0, p1, p2, p3, p4);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileRef_1_0_MakeDirectory");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Bool p1 = get_value_PP_Bool();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileRef_1_0_MakeDirectory)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_FileRef_1_0_Rename");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Resource p1 = get_value_PP_Resource();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_FileRef_1_0_Rename)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_Font_Dev_0_6_GetFontFamilies");
  {
    PP_Instance p0 = get_value_PP_Instance();
    struct PP_Var res = PREFIX_INVOCATION(PPB_Font_Dev_0_6_GetFontFamilies)(p0);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_IMEInputEvent_Dev_0_2_Create");
  {
    PP_Instance p0 = get_value_PP_Instance();
    PP_InputEvent_Type p1 = get_value_PP_InputEvent_Type();
    PP_TimeTicks p2 = get_value_PP_TimeTicks();
    struct PP_Var p3 = get_value_struct_PP_Var();
    uint32_t p4 = get_value_uint32_t();
    const uint32_t* p5 = get_value_uint32_t_ptr();
    int32_t p6 = get_value_int32_t();
    uint32_t p7 = get_value_uint32_t();
    uint32_t p8 = get_value_uint32_t();
    PP_Resource res = PREFIX_INVOCATION(PPB_IMEInputEvent_Dev_0_2_Create)(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    emit_string("result:");
    emit_value_PP_Resource(res);
  }
  new_test("PPB_KeyboardInputEvent_1_0_Create");
  {
    PP_Instance p0 = get_value_PP_Instance();
    PP_InputEvent_Type p1 = get_value_PP_InputEvent_Type();
    PP_TimeTicks p2 = get_value_PP_TimeTicks();
    uint32_t p3 = get_value_uint32_t();
    uint32_t p4 = get_value_uint32_t();
    struct PP_Var p5 = get_value_struct_PP_Var();
    PP_Resource res = PREFIX_INVOCATION(PPB_KeyboardInputEvent_1_0_Create)(p0, p1, p2, p3, p4, p5);
    emit_string("result:");
    emit_value_PP_Resource(res);
  }
  new_test("PPB_MessageLoop_Dev_0_1_PostWork");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_CompletionCallback p1 = get_value_struct_PP_CompletionCallback();
    int64_t p2 = get_value_int64_t();
    int32_t res = PREFIX_INVOCATION(PPB_MessageLoop_Dev_0_1_PostWork)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_Messaging_1_0_PostMessage");
  {
    PP_Instance p0 = get_value_PP_Instance();
    struct PP_Var p1 = get_value_struct_PP_Var();
    PREFIX_INVOCATION(PPB_Messaging_1_0_PostMessage)(p0, p1);
  }
  new_test("PPB_MouseInputEvent_1_1_GetMovement");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_Point res = PREFIX_INVOCATION(PPB_MouseInputEvent_1_1_GetMovement)(p0);
    emit_string("result:");
    emit_value_struct_PP_Point(res);
  }
  new_test("PPB_MouseLock_1_0_LockMouse");
  {
    PP_Instance p0 = get_value_PP_Instance();
    struct PP_CompletionCallback p1 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_MouseLock_1_0_LockMouse)(p0, p1);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_Printing_Dev_0_7_GetDefaultPrintSettings");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_PrintSettings_Dev* p1 = get_value_struct_PP_PrintSettings_Dev_ptr();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_Printing_Dev_0_7_GetDefaultPrintSettings)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_Testing_Dev_0_9_GetDocumentURL");
  {
    PP_Instance p0 = get_value_PP_Instance();
    struct PP_URLComponents_Dev* p1 = get_value_struct_PP_URLComponents_Dev_ptr();
    struct PP_Var res = PREFIX_INVOCATION(PPB_Testing_Dev_0_9_GetDocumentURL)(p0, p1);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_TouchInputEvent_1_0_GetTouchById");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_TouchListType p1 = get_value_PP_TouchListType();
    uint32_t p2 = get_value_uint32_t();
    struct PP_TouchPoint res = PREFIX_INVOCATION(PPB_TouchInputEvent_1_0_GetTouchById)(p0, p1, p2);
    emit_string("result:");
    emit_value_struct_PP_TouchPoint(res);
  }
  new_test("PPB_URLLoader_1_0_ReadResponseBody");
  {
    PP_Resource p0 = get_value_PP_Resource();
    void* p1 = get_value_void_ptr();
    int32_t p2 = get_value_int32_t();
    struct PP_CompletionCallback p3 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_URLLoader_1_0_ReadResponseBody)(p0, p1, p2, p3);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_URLRequestInfo_1_0_SetProperty");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_URLRequestProperty p1 = get_value_PP_URLRequestProperty();
    struct PP_Var p2 = get_value_struct_PP_Var();
    PP_Bool res = PREFIX_INVOCATION(PPB_URLRequestInfo_1_0_SetProperty)(p0, p1, p2);
    emit_string("result:");
    emit_value_PP_Bool(res);
  }
  new_test("PPB_URLResponseInfo_1_0_GetProperty");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_URLResponseProperty p1 = get_value_PP_URLResponseProperty();
    struct PP_Var res = PREFIX_INVOCATION(PPB_URLResponseInfo_1_0_GetProperty)(p0, p1);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_URLUtil_Dev_0_6_Canonicalize");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    struct PP_URLComponents_Dev* p1 = get_value_struct_PP_URLComponents_Dev_ptr();
    struct PP_Var res = PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_Canonicalize)(p0, p1);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_URLUtil_Dev_0_6_DocumentCanRequest");
  {
    PP_Instance p0 = get_value_PP_Instance();
    struct PP_Var p1 = get_value_struct_PP_Var();
    PP_Bool res = PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_DocumentCanRequest)(p0, p1);
    emit_string("result:");
    emit_value_PP_Bool(res);
  }
  new_test("PPB_URLUtil_Dev_0_6_IsSameSecurityOrigin");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    struct PP_Var p1 = get_value_struct_PP_Var();
    PP_Bool res = PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_IsSameSecurityOrigin)(p0, p1);
    emit_string("result:");
    emit_value_PP_Bool(res);
  }
  new_test("PPB_URLUtil_Dev_0_6_ResolveRelativeToDocument");
  {
    PP_Instance p0 = get_value_PP_Instance();
    struct PP_Var p1 = get_value_struct_PP_Var();
    struct PP_URLComponents_Dev* p2 = get_value_struct_PP_URLComponents_Dev_ptr();
    struct PP_Var res = PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_ResolveRelativeToDocument)(p0, p1, p2);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_URLUtil_Dev_0_6_ResolveRelativeToURL");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    struct PP_Var p1 = get_value_struct_PP_Var();
    struct PP_URLComponents_Dev* p2 = get_value_struct_PP_URLComponents_Dev_ptr();
    struct PP_Var res = PREFIX_INVOCATION(PPB_URLUtil_Dev_0_6_ResolveRelativeToURL)(p0, p1, p2);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_Var_1_0_AddRef");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    PREFIX_INVOCATION(PPB_Var_1_0_AddRef)(p0);
  }
  new_test("PPB_Var_1_0_VarFromUtf8");
  {
    PP_Module p0 = get_value_PP_Module();
    const char* p1 = get_value_char_ptr();
    uint32_t p2 = get_value_uint32_t();
    struct PP_Var res = PREFIX_INVOCATION(PPB_Var_1_0_VarFromUtf8)(p0, p1, p2);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_Var_1_0_VarToUtf8");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    uint32_t* p1 = get_value_uint32_t_ptr();
    const char* res = PREFIX_INVOCATION(PPB_Var_1_0_VarToUtf8)(p0, p1);
    emit_string("result:");
    emit_value_char_ptr(res);
  }
  new_test("PPB_Var_1_1_VarFromUtf8");
  {
    const char* p0 = get_value_char_ptr();
    uint32_t p1 = get_value_uint32_t();
    struct PP_Var res = PREFIX_INVOCATION(PPB_Var_1_1_VarFromUtf8)(p0, p1);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_VarArrayBuffer_1_0_ByteLength");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    uint32_t* p1 = get_value_uint32_t_ptr();
    PP_Bool res = PREFIX_INVOCATION(PPB_VarArrayBuffer_1_0_ByteLength)(p0, p1);
    emit_string("result:");
    emit_value_PP_Bool(res);
  }
  new_test("PPB_VarArrayBuffer_1_0_Create");
  {
    uint32_t p0 = get_value_uint32_t();
    struct PP_Var res = PREFIX_INVOCATION(PPB_VarArrayBuffer_1_0_Create)(p0);
    emit_string("result:");
    emit_value_struct_PP_Var(res);
  }
  new_test("PPB_VarArrayBuffer_1_0_Map");
  {
    struct PP_Var p0 = get_value_struct_PP_Var();
    void* res = PREFIX_INVOCATION(PPB_VarArrayBuffer_1_0_Map)(p0);
    emit_string("result:");
    emit_value_void_ptr(res);
  }
  new_test("PPB_VideoCapture_Dev_0_2_Open");
  {
    PP_Resource p0 = get_value_PP_Resource();
    PP_Resource p1 = get_value_PP_Resource();
    const struct PP_VideoCaptureDeviceInfo_Dev* p2 = get_value_struct_PP_VideoCaptureDeviceInfo_Dev_ptr();
    uint32_t p3 = get_value_uint32_t();
    struct PP_CompletionCallback p4 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_VideoCapture_Dev_0_2_Open)(p0, p1, p2, p3, p4);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_VideoDecoder_Dev_0_16_Decode");
  {
    PP_Resource p0 = get_value_PP_Resource();
    const struct PP_VideoBitstreamBuffer_Dev* p1 = get_value_struct_PP_VideoBitstreamBuffer_Dev_ptr();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_VideoDecoder_Dev_0_16_Decode)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_WebSocket_1_0_Close");
  {
    PP_Resource p0 = get_value_PP_Resource();
    uint16_t p1 = get_value_uint16_t();
    struct PP_Var p2 = get_value_struct_PP_Var();
    struct PP_CompletionCallback p3 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_WebSocket_1_0_Close)(p0, p1, p2, p3);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_WebSocket_1_0_Connect");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_Var p1 = get_value_struct_PP_Var();
    const struct PP_Var* p2 = get_value_struct_PP_Var_ptr();
    uint32_t p3 = get_value_uint32_t();
    struct PP_CompletionCallback p4 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_WebSocket_1_0_Connect)(p0, p1, p2, p3, p4);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_WebSocket_1_0_ReceiveMessage");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_Var* p1 = get_value_struct_PP_Var_ptr();
    struct PP_CompletionCallback p2 = get_value_struct_PP_CompletionCallback();
    int32_t res = PREFIX_INVOCATION(PPB_WebSocket_1_0_ReceiveMessage)(p0, p1, p2);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_WebSocket_1_0_SendMessage");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_Var p1 = get_value_struct_PP_Var();
    int32_t res = PREFIX_INVOCATION(PPB_WebSocket_1_0_SendMessage)(p0, p1);
    emit_string("result:");
    emit_value_int32_t(res);
  }
  new_test("PPB_WheelInputEvent_1_0_GetDelta");
  {
    PP_Resource p0 = get_value_PP_Resource();
    struct PP_FloatPoint res = PREFIX_INVOCATION(PPB_WheelInputEvent_1_0_GetDelta)(p0);
    emit_string("result:");
    emit_value_struct_PP_FloatPoint(res);
  }
}

}  // extern "C"


int PREFIX_FUNCTION(main)(int argc, char* argv[]) {
  initialize(argc, argv);
  PREFIX_FUNCTION(test_all)();
  return 0;
}
