// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CONTENT_PUBLIC_COMMON_SCREEN_ORIENTATION_VALUES_H_
#define CONTENT_PUBLIC_COMMON_SCREEN_ORIENTATION_VALUES_H_

namespace content {

// A Java counterpart will be generated for this enum.
// GENERATED_JAVA_ENUM_PACKAGE: org.chromium.content_public.common
enum ScreenOrientationValues {
  SCREEN_ORIENTATION_VALUES_DEFAULT,
  SCREEN_ORIENTATION_VALUES_PORTRAIT_PRIMARY,
  SCREEN_ORIENTATION_VALUES_PORTRAIT_SECONDARY,
  SCREEN_ORIENTATION_VALUES_LANDSCAPE_PRIMARY,
  SCREEN_ORIENTATION_VALUES_LANDSCAPE_SECONDARY,
  SCREEN_ORIENTATION_VALUES_ANY,
  SCREEN_ORIENTATION_VALUES_LANDSCAPE,
  SCREEN_ORIENTATION_VALUES_PORTRAIT,
  SCREEN_ORIENTATION_VALUES_NATURAL,
  SCREEN_ORIENTATION_VALUES_LAST = SCREEN_ORIENTATION_VALUES_NATURAL
};

} // namespace content

#endif  // CONTENT_PUBLIC_COMMON_SCREEN_ORIENTATION_VALUES_H_
