#!/usr/bin/python
# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Command line frontend for Memory Inspector"""

import sys

from memory_inspector.frontends import command_line


if __name__ == '__main__':
  sys.exit(command_line.main())
