Clipboard
=========

Many of the steps in this tutorial will be easier to copy and paste
into the Dev Environment.
To copy and paste in the Dev Environment App,
you will need to use the keyboard.

On your platform use:

  * |copy_key| to Copy
  * |paste_key| to Paste

.. |copy_key| raw:: html

  <span id="copy_key">Loading...</span>
  <script>
  var tag = document.getElementById('copy_key');
  if (navigator.appVersion.indexOf('Mac') >= 0) {
    tag.innerHTML = '&#8984;-C';
  } else {
    tag.innerHTML = 'Ctrl-Shift-C';
  }
  </script>

.. |paste_key| raw:: html

  <span id="paste_key">Loading...</span>
  <script>
  var tag = document.getElementById('paste_key');
  if (navigator.appVersion.indexOf('Mac') >= 0) {
    tag.innerHTML = '&#8984;-V';
  } else {
    tag.innerHTML = 'Ctrl-Shift-V';
  }
  </script>
