Editing
```````

To follow along in this codelab, you'll need to use a text editor to modify
various files in our development environment.
There are currently two editor options, nano or vim.
We have an Emacs port, but it is not yet available in the Dev Environment
(coming soon).
If you're unsure what to pick, nano is simpler to start with and has on-screen
help.

* You can open **nano** like this::

    $ nano <filename>

  Here's an online `nano tutorial <http://mintaka.sdsu.edu/reu/nano.html>`_.

* You can open **vim** like this::

    $ vim <filename>

  Here's an online `vim tutorial <http://www.openvim.com/tutorial.html>`_.
