Setup
-----

For this codelab, you will need to install the our
Beta NaCl Dev Environment App in your web browser.

.. raw:: html

  <a href="https://chrome.google.com/webstore/detail/nacl-development-environm/aljpgkjeipgnmdpikaajmnepbcfkglfa"
  target="_blank">Click here to install the environment.</a>

You will need to click "Install" to add the NaCl Dev Environment
to your browser.

NOTE: This environment will leave a substantial (800MB) payload in your
browser. See the cleanup section below to learn how to recover this space.

Once the installation is complete, run the app.

On the first run, it will download several packages.
Once download is complete, you should see a bash prompt::

  bash.nmf-4.3$

.. include:: ../nacldev/web_tools_note.inc

.. include:: ../nacldev/navigating.inc

.. include:: ../nacldev/clipboard_app.inc

.. include:: ../nacldev/editing.inc

.. include:: ../nacldev/git.inc
