Our Web-based Tools
===================

These development tools are a `work in progress <nacldev>`_.
At this point, they are a learning tool and demonstration of NaCl's
flexibility, but are not the recommended tools for a production application.
In the future, that may change, but for the moment,
to develop a substantial application for Native Client /
Portable Native Client,
we recommend you use the
`Native Client SDK </native-client/sdk/download>`_.

.. raw:: html

  <b><font color="#880000">
  NOTE: The NaCl Development Environment is not yet stable.
  Ideally, user data is preserved, but currently it can be lost during updates
  or sporadically. We're working to resolve this.
  </font></b>
