#!/usr/bin/env python

# Copyright 2018 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Copies file_manager/main.html to file_manager/test.html.

Modifies it to be able to run the CrOS FileManager app
as a regular web page in a single renderer.
"""


import argparse
import os
import sys


assert __name__ == '__main__'

parser = argparse.ArgumentParser()
parser.add_argument('--output')
args = parser.parse_args()

# ROOT=//ui/file_manager/file_manager
ROOT = os.path.abspath(os.path.join(sys.path[0], '../..'))
scripts = []
GENERATED_HTML = ('<!-- Generated by:\n  -- ui/file_manager/file_manager/'
                  'tests/scripts/create_test_main.py\n  -->\n\n')
GENERATED_JS = ('// Generated by:\n// ui/file_manager/file_manager/'
                'tests/scripts/create_test_main.py\n\n')


def read(path):
  with open(os.path.join(ROOT, path)) as f:
    return f.read()


def write(path, content):
  fullpath = os.path.join(ROOT, path)
  if not os.path.exists(os.path.dirname(fullpath)):
    os.makedirs(os.path.dirname(fullpath))
  with open(fullpath, 'w') as f:
    f.write(content)


def replaceline(f, match, lines):
  """Replace matching line in file with lines."""
  for i in range(len(f)):
    if match in f[i]:
      return f[:i] + lines + f[i+1:]
  return f


def includes2scripts(include_filename):
  """Convert <include src='foo'> to <script src='<prefix>foo'></script>."""
  scripts.append('<!-- %s -->' % include_filename)
  prefix = include_filename[:include_filename.rindex('/')+1]
  f = read(include_filename).split('\n')
  for i in range(len(f)):
    l = f[i]
    # Join back any include with a line-break.
    if l == '// <include' and f[i+1].startswith('// src='):
      f[i+1] = l + f[i+1][2:]
      continue
    if l.startswith('// <include '):
      l = l.replace('// <include ', '<script ')
      # Special fix for analytics.
      if 'webui/resources/js/analytics.js' in l:
        l = l.replace('webui/resources/js/analytics.js',
                      '../third_party/analytics/google-analytics-bundle.js')
      # main.js should be defer.
      if 'src="main.js"' in l:
        l = l.replace('src="main.js"', 'src="main.js" defer')
      # Fix the path for scripts to be relative to ROOT.
      if 'src="../../' in l:
        l = l.replace('src="../../', 'src="')
      else:
        l = l.replace('src="', 'src="' + prefix)
      tag = l + '</script>'
      if tag not in scripts:
        scripts.append(tag)

# Fix link to action_link.css and text_defaults.css.
main_html = (read('main.html')
             .replace('chrome://resources/css/action_link.css',
                      '../../webui/resources/css/action_link.css')
             .replace('chrome://resources/css/text_defaults.css',
                      'test/gen/css/text_defaults.css')
             .split('\n'))

# Fix text_defaults.css.  Copy and replace placeholders.
text_defaults = (read('../../webui/resources/css/text_defaults.css')
                 .replace('$i18n{textDirection}', 'ltr')
                 .replace('$i18nRaw{fontFamily}', 'Roboto, sans-serif')
                 .replace('$i18nRaw{fontSize}', '75%'))
write('test/gen/css/text_defaults.css', GENERATED_HTML + text_defaults)

# Fix stylesheet from extension.
main_html = replaceline(
    main_html,
    ('chrome-extension://fbjakikfhfdajcamjleinfciajelkpek/'
     'cws_widget/cws_widget_container.css'),
    [('<link rel="stylesheet" href="../../../components/chrome_apps/'
      'webstore_widget/cws_widget/cws_widget_container.css">')])

# Add scripts required for testing, and the test files (test/*.js).
scripts.append('<!-- required for testing -->')
scripts += ['<script src="%s"></script>' % s for s in [
    'test/js/chrome_api_test_impl.js',
    '../../webui/resources/js/assert.js',
    '../../webui/resources/js/cr.js',
    '../../webui/resources/js/cr/event_target.js',
    '../../webui/resources/js/cr/ui/array_data_model.js',
    '../../webui/resources/js/load_time_data.js',
    '../../webui/resources/js/webui_resource_test.js',
    'test/js/strings.js',
    'common/js/util.js',
    'common/js/mock_entry.js',
    'common/js/volume_manager_common.js',
    'background/js/volume_info_impl.js',
    'background/js/volume_info_list_impl.js',
    'background/js/volume_manager_impl.js',
    'background/js/mock_volume_manager.js',
    'foreground/js/constants.js',
    'test/js/chrome_file_manager.js',
    'test/js/test_util.js',
] + ['test/' + s for s in os.listdir(os.path.join(ROOT, 'test'))
     if s.endswith('.js')]]

# Convert all includes from:
#  * foreground/js/main_scripts.js
#  * background/js/background_common_scripts.js
#  * background/js/background_scripts.js
# into <script> tags in main.html.
# Add polymer libs at start.
bg_scripts = read('background/js/background_scripts.js').split('\n')
includes2scripts('foreground/js/main_scripts.js')
includes2scripts('background/js/background_common_scripts.js')
includes2scripts('background/js/background_scripts.js')
main_html = replaceline(main_html, 'foreground/js/main_scripts.js', [
    ('<link rel="import" href="../../../third_party/polymer/v1_0/'
     'components-chromium/polymer/polymer.html">'),
    ('<link rel="import" href="../../../third_party/polymer/v1_0/'
     'components-chromium/paper-progress/paper-progress.html">'),
    ] + scripts)

# Load QuickView in iframe rather than webview.
# Change references in files_quick_view.html to use updated
# files_safe_media.html which will use webview rather than iframe,
# and sets src directly on iframe.
for filename, substitutions in (
    ('elements/files_quick_view.html', (
        ('="files_icon', '="../../../foreground/elements/files_icon'),
        ('="files_metadata', '="../../../foreground/elements/files_metadata'),
        ('="files_tooltip', '="../../../foreground/elements/files_tooltip'),
        ('="files_quick', '="../../../foreground/elements/files_quick'),
        ('="icons', '="../../../foreground/elements/icons'),
        ('webview', 'iframe'),
    )),
    ('elements/files_safe_media.html', (('webview', 'iframe'),)),
    ('elements/files_safe_media.js', (
        ("'webview'", "'iframe'"),
        ("'contentload'", "'load'"),
        ('this.webview_.contentWindow.postMessage(data, FILES_APP_ORIGIN);',
         ('this.webview_.contentWindow.content.type = this.type;'
          'this.webview_.contentWindow.content.src = this.src;')),
    )),
    ):
  buf = read('foreground/' + filename)
  for old, new in substitutions:
    buf = buf.replace(old, new)
  write('test/gen/' + filename, GENERATED_JS + buf)
  main_html = replaceline(main_html, 'foreground/' + filename,
                          ['<script src="test/gen/%s"></script>' % filename])

test_html = GENERATED_HTML + '\n'.join(main_html)
write('test.html', test_html)

# If --output is provided, also create specified file.
if args.output:
  with open(args.output, 'w') as output:
    output.write(test_html)
