{
  'SEARCH': [
    '../../../../third_party/googletest/src/googlemock',
  ],
  'DATA': [
    'src/gmock.cc',
    'src/gmock-all.cc',
    'src/gmock-matchers.cc',
    'src/gmock-cardinalities.cc',
    'src/gmock-internal-utils.cc',
    'src/gmock-spec-builders.cc',
    'include/gmock/gmock-actions.h',
    'include/gmock/gmock-cardinalities.h',
    'include/gmock/gmock-generated-actions.h',
    'include/gmock/gmock-generated-actions.h.pump',
    'include/gmock/gmock-generated-function-mockers.h',
    'include/gmock/gmock-generated-function-mockers.h.pump',
    'include/gmock/gmock-generated-matchers.h',
    'include/gmock/gmock-generated-matchers.h.pump',
    'include/gmock/gmock-generated-nice-strict.h',
    'include/gmock/gmock-generated-nice-strict.h.pump',
    'include/gmock/gmock.h',
    'include/gmock/gmock-matchers.h',
    'include/gmock/gmock-more-actions.h',
    'include/gmock/gmock-more-matchers.h',
    'include/gmock/gmock-spec-builders.h',
    'include/gmock/internal/gmock-generated-internal-utils.h',
    'include/gmock/internal/gmock-generated-internal-utils.h.pump',
    'include/gmock/internal/gmock-internal-utils.h',
    'include/gmock/internal/gmock-port.h',
    'include/gmock/internal/custom/gmock-generated-actions.h',
    'include/gmock/internal/custom/gmock-matchers.h',
    'include/gmock/internal/custom/gmock-port.h',
  ],
  'DEST': 'src',
  'NAME': 'gmock',
}
