{{+bindTo:partials.standard_nacl_api}}
<h1>PPB_OpenGLES2FramebufferMultisample Struct Reference</h1>
<div id="doxygen-ref">
{{- dummy div to appease doxygen -}}
  <div>
<!-- Generated by Doxygen 1.7.6.1 -->


</div>
<!--header-->
<div class="contents">
<!-- doxytag: class="PPB_OpenGLES2FramebufferMultisample" --><h2>
Data Fields</h2><table class="memberdecls">

<tr><td class="memItemLeft" align="right" valign="top">void(*&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="struct_p_p_b___open_g_l_e_s2_framebuffer_multisample.html#ae9a2335014f42388fe445c023309aa4f">RenderbufferStorageMultisampleEXT</a> )(<a class="el" href="group___typedefs.html#gafdc3895ee80f4750d0d95ae1b677e9b7">PP_Resource</a> context, <a class="el" href="ppb__opengles2_8h.html#a7efd7809e1632cdae75603fd1fee61c0">GLenum</a> target, <a class="el" href="ppb__opengles2_8h.html#a9289d5b99dc1f27f01480360f2e18ae0">GLsizei</a> samples, <a class="el" href="ppb__opengles2_8h.html#a7efd7809e1632cdae75603fd1fee61c0">GLenum</a> internalformat, <a class="el" href="ppb__opengles2_8h.html#a9289d5b99dc1f27f01480360f2e18ae0">GLsizei</a> width, <a class="el" href="ppb__opengles2_8h.html#a9289d5b99dc1f27f01480360f2e18ae0">GLsizei</a> height)</td></tr>
</table>
<hr /><h2>Field Documentation</h2>
<a class="anchor" id="ae9a2335014f42388fe445c023309aa4f"></a><!-- doxytag: member="PPB_OpenGLES2FramebufferMultisample::RenderbufferStorageMultisampleEXT" ref="ae9a2335014f42388fe445c023309aa4f" args=")(PP_Resource context, GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)" -->
<div class="memitem">
<div class="memproto">
<table class="memname">
<tr>
<td class="memname">void(* <a class="el" href="struct_p_p_b___open_g_l_e_s2_framebuffer_multisample.html#ae9a2335014f42388fe445c023309aa4f">PPB_OpenGLES2FramebufferMultisample::RenderbufferStorageMultisampleEXT</a>)(<a class="el" href="group___typedefs.html#gafdc3895ee80f4750d0d95ae1b677e9b7">PP_Resource</a> context, <a class="el" href="ppb__opengles2_8h.html#a7efd7809e1632cdae75603fd1fee61c0">GLenum</a> target, <a class="el" href="ppb__opengles2_8h.html#a9289d5b99dc1f27f01480360f2e18ae0">GLsizei</a> samples, <a class="el" href="ppb__opengles2_8h.html#a7efd7809e1632cdae75603fd1fee61c0">GLenum</a> internalformat, <a class="el" href="ppb__opengles2_8h.html#a9289d5b99dc1f27f01480360f2e18ae0">GLsizei</a> width, <a class="el" href="ppb__opengles2_8h.html#a9289d5b99dc1f27f01480360f2e18ae0">GLsizei</a> height)</td>
</tr>
</table>
</div>
<div class="memdoc">
</div>
</div>
<hr />The documentation for this struct was generated from the following file:<ul>
<li><a class="el" href="ppb__opengles2_8h.html">ppb_opengles2.h</a></li>
</ul>
</div><!-- contents -->
</div>
{{/partials.standard_nacl_api}}
