// This file was generated by the _js_query_arg_file Skylark rule defined in
// maps/vectortown/performance/script/build_defs.bzl.

var testConfig = "overridePixelRatio=1&title=chrome_smoothness_performancetest_config&nobudget=false&nodraw=false&noprefetch=true&viewport=basic&wait=true";
