// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// MeasurePageLoadTime.idl : IDL source for MeasurePageLoadTime
//

// This file will be processed by the MIDL tool to
// produce the type library (MeasurePageLoadTime.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(019637EB-B865-485B-9A66-419477EE55A0),
	dual,
	nonextensible,
	helpstring("IMeasurePageLoadTimeBHO Interface"),
	pointer_default(unique)
]
interface IMeasurePageLoadTimeBHO : IDispatch{
};
[
	uuid(61AC7AC4-B715-4955-A238-5F9AEA80DF4B),
	version(1.0),
	helpstring("MeasurePageLoadTime 1.0 Type Library")
]
library MeasurePageLoadTimeLib
{
	importlib("stdole2.tlb");
	[
		uuid(807E68BC-238F-4163-AE4B-0A3604F3E145),
		helpstring("MeasurePageLoadTimeBHO Class")
	]
	coclass MeasurePageLoadTimeBHO
	{
		[default] interface IMeasurePageLoadTimeBHO;
	};
};
