// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Private API for reporting Chrome browser status to admin console.
namespace enterprise.reportingPrivate {

  // Invoked by <code>UploadChromeDesktopReport</code> when the upload is
  // finished.
  callback DoneCallback = void();

  interface Functions {

    // Uploads the status of Chrome browser to the admin console by sending
    // request to the DMServer. Sets runtime.lastError on failure.
    static void uploadChromeDesktopReport(
        object report,
        optional DoneCallback callback);
  };

};
