// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Private API to initiate inline install flow of other apps.
namespace inlineInstallPrivate {

  // This returns a developer-readable error message in error and
  // a string error code in errorCode (see $ref:webstore.ErrorCode)
  callback ResultCallback = void (DOMString error,
                                  DOMString errorCode);

  interface Functions {
    // This can currently only be used to install apps, but not extensions.
    static void install(DOMString id,
                        optional ResultCallback callback);
  };
};
