//misesPrivate function
namespace misesPrivate {
  callback GetInstallReferrerCallback = void(DOMString installReferrer);
  interface Functions {
    // set mises id
    static void setMisesId(DOMString id);
    static void getInstallReferrer(GetInstallReferrerCallback callback);
  };
};
